### ISSUE TITLE
作者看到请回答

### ISSUE THREAD

**Issue by xinstart-0** [angus-cx/SubCase#2]
sub-store开发组邀请你进组，只不过没有你的联系方式
![Screenshot_20241011_205218_org.thunderdog.challegram_edit_616780508565779.jpg](https://github.com/user-attachments/assets/a742ef55-e5b3-4639-b337-22dd9491b9f4)

**Comment by sionnx** [comment]
收到，已和一一联系上 🤣

**Comment by OSNewbie** [comment]
安卓端使用好像少了一个东西，没有分流规则，导入进去好像也没有作用，无法使用
感觉有点像硬伤

**Comment by sionnx** [comment]
> 安卓端使用好像少了一个东西，没有分流规则，导入进去好像也没有作用，无法使用 感觉有点像硬伤

为了方便跟踪问题，请新建issue

**Comment by OSNewbie** [comment]
![Image](https://github.com/user-attachments/assets/9cd643a6-9a0c-4678-8f01-91272e60a095)

> > 安卓端使用好像少了一个东西，没有分流规则，导入进去好像也没有作用，无法使用 感觉有点像硬伤
> 
> 为了方便跟踪问题，请新建issue

算了，我还是直接说吧

1.订阅管理 预览/拷贝订阅 目前只提供节点信息，没有分流规则导入代理工具没有用 
2.文件管理 只能用本地上传对应的分流配置文件生成对应的分流规则  远程都不知道什么原因拉不下了可能是分流规则不兼容明明都是yaml文件 猜测应该是有些配置文件中的参数 格式不规范导致的问题

我看别人他们说是通过脚本来实现，但是你觉得大家都会不成，看到上面提示，需要通过参数来实现，但是你默认的他没有带分流规则的参数案例标准
不是人人都会手搓配置

我希望是跟那种订阅转换一样的，要么内置规则，要么就可以添加规则的形式，苹果生态的代理工具转换，想转到安卓适配规则感觉难度挺大的

划线的是代表可能常用的安卓代理工具

希望是适配 SubCase安卓端更新上分流规则就行了

**Comment by sionnx** [comment]
subcase 是基于 sub-store  的在 Android上的封装，你提的这些问题，好像是 sub-store 的，如果是的话， 请到该仓库提交 issue https://github.com/sub-store-org/Sub-Store
